### ISSUE TITLE
Multi-file editing

### ISSUE THREAD

**Issue by MirrorPusher** [FilipVanVooren/stevie#25]
Add possibility to edit multiple files simultaneously.

Have up to 10 editor buffers (accessible via shortcuts ctrl-0 to ctrl-9). 
In addition to that some kind of clipboard is needed to allow copying/moving file snippets accross editor buffers.

**Comment by FilipVanVooren** [comment]
Probably not going to happen. With the newly introduced file picker and catalog functionality in Stevie 1.5.20 it is very easy to jump between files. The implementation effort required is too high, as the already available functionality has >80% of what we want to accomplish here.
