### ISSUE TITLE
Rename 'Configure' main menu entry to 'Options'

### ISSUE THREAD

**Issue by FilipVanVooren** [FilipVanVooren/stevie#75]
Rename 'Configure' main menu entry to 'Options', as it already has the shortcut key 'o' anyway.

Tasks:
- Rename main menu entry
- Rename dialog header
- Rename source file name

**Comment by KhadijaKamran** [comment]
I would like to contribute to this issue

**Comment by FilipVanVooren** [comment]
Implemented in Stevie 1.4E
